### PR TITLE
Bugfix trade

### PR DESCRIPTION
**Pull request by JueMueller**
fixed a bug in Trade due to live data from IB; please verify possible data format of tradeDate and tradeTime sent by IB

### CODE REVIEW

**Comment by gabbersepp** [comment]
Can you please explain, what was wrong with the current code?

**Comment by JueMueller** [comment]
I've added some data retrieved from IB via FlexQuery. The value for tradeDate is always a date without time, as expected (e.g. tradeDate="20190524"). The value for tradeTime is not sent. Such a line will not be read without the changes of this pull request, but will result in an error.  

Please verify the content of **tradeDate** and **tradeTime** in your data. 

```
<FlexQueryResponse queryName="2019_xml" type="AF">
<FlexStatements count="1">
<FlexStatement accountId="abc" fromDate="20190102" toDate="20190704" period="YearToDate" whenGenerated="20190705;085855">
<Trades>
<Trade accountId="abc" acctAlias="" model="" currency="USD" fxRateToBase="0.89233" assetCategory="STK" symbol="ALSN" description="ALLISON TRANSMISSION HOLDING" conid="104054141" securityID="" securityIDType="" cusip="" isin="" listingExchange="NYSE" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" tradeID="2448999983" putCall="" reportDate="20190524" principalAdjustFactor="" dateTime="20190524;110508" tradeDate="20190524" settleDateTarget="20190529" transactionType="ExchTrade" exchange="DARK" quantity="-100" tradePrice="42.4725" tradeMoney="-4247.25" proceeds="4247.25" taxes="0" ibCommission="-5" ibCommissionCurrency="USD" netCash="4242.25" closePrice="42.64" openCloseIndicator="O" notes="" cost="-4242.25" fifoPnlRealized="0" fxPnl="0" mtmPnl="-16.75" origTradePrice="0" origTradeDate="" origTradeID="" origOrderID="0" clearingFirmID="" transactionID="10735803236" buySell="SELL" ibOrderID="1202053016" ibExecID="0001506d.5ce7e573.01.01" brokerageOrderID="001045e8.0001ab90.5ce7703b.0001" orderReference="" volatilityOrderLink="" exchOrderId="N/A" extExecID="23810252" orderTime="20190524;110502" openDateTime="" holdingPeriodDateTime="" whenRealized="" whenReopened="" levelOfDetail="EXECUTION" changeInPrice="0" changeInQuantity="0" orderType="LMT" traderID="C1" isAPIOrder="N" />
<Trade accountId="abc" acctAlias="" model="" currency="USD" fxRateToBase="0.89114" assetCategory="STK" symbol="ALSN" description="ALLISON TRANSMISSION HOLDING" conid="104054141" securityID="" securityIDType="" cusip="" isin="" listingExchange="NYSE" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" tradeID="2458345389" putCall="" reportDate="20190605" principalAdjustFactor="" dateTime="20190605;100910" tradeDate="20190605" settleDateTarget="20190607" transactionType="ExchTrade" exchange="IBKRATS" quantity="100" tradePrice="43.61" tradeMoney="4361" proceeds="-4361" taxes="0" ibCommission="-5" ibCommissionCurrency="USD" netCash="-4366" closePrice="44.07" openCloseIndicator="C" notes="" cost="4242.25" fifoPnlRealized="-123.75" fxPnl="0" mtmPnl="46" origTradePrice="0" origTradeDate="" origTradeID="" origOrderID="0" clearingFirmID="" transactionID="10787299894" buySell="BUY" ibOrderID="1206562196" ibExecID="0000db5b.5cf7be60.01.01" brokerageOrderID="001045e8.0001ab90.5cf74240.0001" orderReference="" volatilityOrderLink="" exchOrderId="N/A" extExecID="203566700B" orderTime="20190605;100910" openDateTime="" holdingPeriodDateTime="" whenRealized="" whenReopened="" levelOfDetail="EXECUTION" changeInPrice="0" changeInQuantity="0" orderType="LMT" traderID="C1" isAPIOrder="N" />
<Trade accountId="abc" acctAlias="" model="" currency="USD" fxRateToBase="0.89015" assetCategory="STK" symbol="AMD" description="ADVANCED MICRO DEVICES" conid="4391" securityID="" securityIDType="" cusip="" isin="" listingExchange="NASDAQ" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" tradeID="2401402201" putCall="" reportDate="20190403" principalAdjustFactor="" dateTime="20190403;105109" tradeDate="20190403" settleDateTarget="20190405" transactionType="ExchTrade" exchange="EDGEA" quantity="-100" tradePrice="29.25" tradeMoney="-2925" proceeds="2925" taxes="0" ibCommission="-5" ibCommissionCurrency="USD" netCash="2920" closePrice="29.02" openCloseIndicator="C" notes="" cost="-2343.5" fifoPnlRealized="576.5" fxPnl="0" mtmPnl="23" origTradePrice="0" origTradeDate="" origTradeID="" origOrderID="0" clearingFirmID="" transactionID="10489396954" buySell="SELL" ibOrderID="1178795314" ibExecID="0000d8dc.5ca48a6a.01.01" brokerageOrderID="001045e8.0001ab90.5ca43400.0001" orderReference="" volatilityOrderLink="" exchOrderId="N/A" extExecID="173356543853/S" orderTime="20190403;105109" openDateTime="" holdingPeriodDateTime="" whenRealized="" whenReopened="" levelOfDetail="EXECUTION" changeInPrice="0" changeInQuantity="0" orderType="LMT" traderID="C1" isAPIOrder="N" />
<Trade accountId="abc" acctAlias="" model="" currency="USD" fxRateToBase="0.89594" assetCategory="STK" symbol="BL" description="BLACKLINE INC" conid="253664117" securityID="" securityIDType="" cusip="" isin="" listingExchange="NASDAQ" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" tradeID="2450313187" putCall="" reportDate="20190528" principalAdjustFactor="" dateTime="20190528;113009" tradeDate="20190528" settleDateTarget="20190530" transactionType="ExchTrade" exchange="ISLAND" quantity="49" tradePrice="53.44" tradeMoney="2618.56" proceeds="-2618.56" taxes="0" ibCommission="-5" ibCommissionCurrency="USD" netCash="-2623.56" closePrice="53.01" openCloseIndicator="O" notes="P" cost="2623.56" fifoPnlRealized="0" fxPnl="0" mtmPnl="-21.07" origTradePrice="0" origTradeDate="" origTradeID="" origOrderID="0" clearingFirmID="" transactionID="10744617666" buySell="BUY" ibOrderID="1202678043" ibExecID="00013d66.5ced258c.01.01" brokerageOrderID="001045e8.0001ab90.5cecb618.0001" orderReference="" volatilityOrderLink="" exchOrderId="N/A" extExecID="0323678011" orderTime="20190528;113009" openDateTime="" holdingPeriodDateTime="" whenRealized="" whenReopened="" levelOfDetail="EXECUTION" changeInPrice="0" changeInQuantity="0" orderType="LMT" traderID="C1" isAPIOrder="N" />
<Trade accountId="abc" acctAlias="" model="" currency="USD" fxRateToBase="0.89594" assetCategory="STK" symbol="BL" description="BLACKLINE INC" conid="253664117" securityID="" securityIDType="" cusip="" isin="" listingExchange="NASDAQ" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" tradeID="2450313241" putCall="" reportDate="20190528" principalAdjustFactor="" dateTime="20190528;113009" tradeDate="20190528" settleDateTarget="20190530" transactionType="ExchTrade" exchange="ISLAND" quantity="1" tradePrice="53.44" tradeMoney="53.44" proceeds="-53.44" taxes="0" ibCommission="0" ibCommissionCurrency="USD" netCash="-53.44" closePrice="53.01" openCloseIndicator="O" notes="P" cost="53.44" fifoPnlRealized="0" fxPnl="0" mtmPnl="-0.43" origTradePrice="0" origTradeDate="" origTradeID="" origOrderID="0" clearingFirmID="" transactionID="10744617668" buySell="BUY" ibOrderID="1202678043" ibExecID="00013d66.5ced258b.01.01" brokerageOrderID="001045e8.0001ab90.5cecb618.0001" orderReference="" volatilityOrderLink="" exchOrderId="N/A" extExecID="0323678001" orderTime="20190528;113009" openDateTime="" holdingPeriodDateTime="" whenRealized="" whenReopened="" levelOfDetail="EXECUTION" changeInPrice="0" changeInQuantity="0" orderType="LMT" traderID="C1" isAPIOrder="N" />
</Trades>
</FlexStatement>
</FlexStatements>
</FlexQueryResponse>
```

**Comment by gabbersepp** [comment]
It seems that the Field "TradeTime" has been removed completely from the FlexQuery Konfiguration. There is now a Field "Date/Time" instead. Unfortunatelly the support was not able to tell me wether this replaces the other field. So I will need some time to investigate this :-(

**Comment by gabbersepp** [comment]
The Captrader support told me, that DateTime replaces at least TradeTime, maybe also the TradeDate field. This makes sense, since Date/Time contains both. A test on all of my 2017 Trades shows that Date/Time and TradeDate + TradeTime contains the same content. Unfortunatelly they can not provide me a description of all fields. I will now replace the field as suggested and discard the PR.

**Comment by gabbersepp** [comment]
@JueMueller I have merged your PR to include the new tests. DateTime allows now a "date;time" and "date" only.

**Pull request merged**
