### PR TITLE
Net framework test project

### PR DESCRIPTION
**Pull request by JueMueller**

### CODE REVIEW

**Comment by Hummel83** [comment]
@JueMueller why do you change the test framework?

**Comment by JueMueller** [comment]
> @JueMueller why do you change the test framework?

Owner of gabbersepp:master had problems with the old test project, so he changed the type of the test  project. This  didn't work proper and so I fixed it  (we had a conversation about that topic...)

**Comment by gabbersepp** [comment]
> @JueMueller why do you change the test framework?

My first try was a .NET Core Testproject with NUnit. This leads to some strange behaviour from time to time. E.g. often I was not able to run the tests and had to rebuild the solution x times. Or the tests were shown in the test explorer twice.

I will try the suggested solution and merge the pr. What do you think about this?

**Comment by gabbersepp** [comment]
> switch to mstest is useless. please block this pull request

What would you suggest?

**Comment by Hummel83** [comment]
use my pull request. Your project references was wrong not the testframework

**Comment by gabbersepp** [comment]
> use my pull request. Your project references was wrong not the testframework

I see, I used assembly references instead of project references. No idea why I had done this lol. Thanks, did not see that!

@JueMueller can you try it again if the test project now works for you?

**Comment by JueMueller** [comment]
Yes. It works.

**Pull request closed without merging**
